### ISSUE TITLE
Create "Automated Build' in DockerHub

### ISSUE THREAD

**Issue by ruzickap** [kensanata/fgallery#3]
Hello.

I would like to ask the owner of this repository to create the "Automated Build' in DockerHub. This will ensure, that the image will be always actual.

Feel free to look at my "old" fgallery DockerHub repository: https://hub.docker.com/r/peru/fgallery/

Thank you

**Comment by kensanata** [comment]
Is there a way I can let you handle this?

**Comment by ruzickap** [comment]
Actually this is not possible.
The Docker Hub repository https://hub.docker.com/r/peru/fgallery/ points to "https://github.com/ruzickap/docker-fgallery" GitHub repo - one person needs to own GitHub account and Docker Hub account. 

To have fgallery build from your repository using [Dockerfile](https://github.com/kensanata/fgallery/blob/master/Dockerfile) you need to follow these steps https://docs.docker.com/docker-hub/builds/.
-> It's 10 minute job... so it's not a big deal.

**Comment by kensanata** [comment]
I did that but the automated build seems to be hanging. Any ideas? https://cloud.docker.com/swarm/kensanata/repository/docker/kensanata/fgallery/builds

**Comment by kensanata** [comment]
Well, it just took a long time. Success! So we can close this issue?

**Comment by ruzickap** [comment]
It seems to be fine. [Tests](https://github.com/kensanata/fgallery/blob/master/tests/test.sh) are working fine.

Thank you

Closing...
