### ISSUE TITLE
Rename project

### ISSUE THREAD

**Issue by kensanata** [kensanata/fgallery#6]
Based on [a comment by wavexx](https://github.com/wavexx/fgallery/pull/76#issuecomment-368947439), we should rename this project.
I propose **Sitelen Mute** which is [Toki Pona](https://en.wikipedia.org/wiki/Toki_Pona) for *many pictures*, i.e. a gallery. Any other ideas?
I also thought of "single letter" + "gallery" but the ones I picked all seem to be names for things already existing.

**Comment by kensanata** [comment]
Also rename [docker cloud thing](https://cloud.docker.com/swarm/kensanata/repository/docker/kensanata/fgallery/general).

**Comment by ruzickap** [comment]
What about "zomera" - it means "gallery" in one of the African language: 

https://www.indifferentlanguages.com/words/gallery

:-)

**Comment by kensanata** [comment]
Sounds good! And it is short.

**Comment by ruzickap** [comment]
But it looks like it's probably owned by: `https://www.drugs.com/international/zomera.html`

So maybe `fzomera` or `zomera gallery` would be better... (or maybe something totally different)
(looks like it's not so easy to find the right "name")

It's your project now - so please decide...

**Comment by kensanata** [comment]
Then I will stick to  **sitelen-mute**.

**Comment by ruzickap** [comment]
OK...
